#+TITLE: Leksjonsplan tropp 2 årlig trening 2021
* Leksjonsplan
  * Mandag
    * 12:00 - 17:10 (310 min) Trening enkeltmann og samband
      * Tegn og signaler
      * Avstandsbedømmelse
      * Målangivelse (målbeskrivelse + stedsangivelse), jf 3.2 i Reglement for fotlag.
      * SSDS
      * Magasinbytte og ildhåndgrep
      * Vernemaskedrill?
    * 17:20 - 20:00 (160 min) Stridsdrill 1, 2 og 3a
      * Stridsdrill 1: Hurtig stillingsbesettelse (10 min)
      * Stridsdrill 2: Ild og bevelgelse (15 min)
      * Stridsdrill 3a: Innbrudd i stilling/grop (20 min)
      * Trening i lagene (115 min)
  * Tirsdag
    * 12:50 - 15:30 (160 min) Patruljeteknikk og kontakt
      * Hvilke patruljetekikker skal trenes og hvem skal stå for denne?
      * Stridsdrill 5a: Stridskontakt, vinne ildoverlegenhet
      * Stridsdrill 5b: Stridskontakt, begrenset ildåpning
      * Stridsdrill 5c: Ildstøtte, hurtig angrep
      * Stridsdrill 5d: Stridskontakt, kort hold
    * 15:30 - 20:00 (270 min) SD 5 og MOBO-innføring
      * Fortsette på stridsdrill 5a-d over?
      * Hvem tar MOBO-innføringen?
      * Hvor foregår MOBO-demonstrasjon og trening?
      * Hva må forberedes?
  * Onsdag
    * 07:50 - 16:30 (520 min) MOBO SD 4b innbrudd i bygning, SD 4a rydding av rom, SD 5a kontaktdirll (sanitet er inkludert hele veien)
      
* Leksjon 1: Stridsdrill 1, 2, og 3a
  Følgende er et fullstendig leksjonsopplegg for å gjennomgå stridsdrillene 1, 2 og 3a.

** Mål
   Etter denne leksjonen skal elevene vite hvordan stridsdrill 1 hurtig stillingsbesettelse, 2 ild og bevegelse, og 3a innbrudd i grop/stilling initieres, gjennomføres, og hva som kreves av dem under drillen.

** Forklaring
   Grunnlaget for et lagsangrep er faseinndelingen av angrep:
   * /Lokalisering/ av fienden for å kunne
   * /binde/ fienden med ild, slik at laget kan
   * /manøvrere/ inn på stormavstand, og gjøre
   * /innbrudd/ og rydde fiendens stilling.


   Jeg siterer fra Reglement for fotlag av 14. desember 2010
   #+begin_quote
   Stridsdrillene har til hensikt å fastlegge og stanardisere handlingsmønstre som utgangspunkt for trening på lagsnivå i Hæren. Dette sikrer en enhetlig treningsstandard og begrepsbruk på tvers av bataljonene.
   #+end_quote

   Jeg siterer videre
   #+begin_quote
   "Stridsdrill" er navnet på kollektiv handling utført med begrenset tid til vurdering og tilpasning av hankdlemøte. De må være så godt innlært og øvet at de kan tilpasses ulike situasjoner, terreng og oppdrag[, og] utføres i alle kritiske situasjoner hvor laget er utsatt for frykt og stress.
   #+end_quote

   Når alle i laget vet hva som skal skje og hva de må gjøre når lagføreren gir en ordre for å utføre en stridsdrill, kan laget effektivt bekjempe fienden og bidra til at sjefens intensjon oppnås.

** Fremgangsmåte
   Jeg vil gjennomføre denne leksjonen ved å gjennomgå orderen som lagføreren gir for hver stridsdrill, og vise hva laget gjør ved å bruke Legofigurer på et modellbord. Etter at hver enkelt stridsdrill er gjennomgått vil lagene få tid til å repetere gjennomgangen ved selv å utføre handlingene.

** Repetisjon av noen forutsetninger
   Disse drillene krever at hver enkelt soldat er kjent med
   * Målangivelse
   * Tegn og signaler
   * Formasjoner
   * Avstandsbedømmelse
   * SSDS
   * Magasinbytter og ildhåndgrep


** Stridsdrill 1: Hurtig stillingsbesettelse
   Varighet: 10 minutter
   Metode: Modellbord med Legofigurer

*** Kort innledning
   Benyttes i mange situasjoner, blant annet:
    - Observasjonskontakt med fienden
    - Angrepsoperasjoner
    - Holdt under marsj
    - Når målet er tatt
    - Iverksettelse av hurtig bakhold mot forfølgende fiende


*** Gjennomgang av drillen
    Det benyttes legofigurer til å demonstrere drillen.
     - Lagfører varsler: Hurtig stillingsbesettelse!
     - Videre gir lagfører ordre om retning og formasjon (gjerne linje).
     - Så tar lagfører ut stillingsområdets venstre og høyre begrensning ved å bruke "fra" og "til".
     - Deretter gir lagfører ordre om ildområdet ved å angi venstre og høyre begrensning.
       - Begrensningene vil gjerne overlappe med egne lag til høyre og/eller venstre for oss, og er ment for å sørge for at ingen områder står udekket.
     - For å kunne kommunsere bedre i laget, tar lagfører ut grunnpunkter i ildområdet. Dette forenkler stedsangivelsen.
     - Ildåpningsbestemmelsene angir i hvilken situasjon det skal åpnes ild
       - På ordre
       - Avstand
       - Ildåpningslinje
       - Fri
       - Ildforbud
       - Retten til selvforsvar
     - Til slutt gir lagføreren ordre om stillingsutbedring
    
*** Viktige momenter
    Det er viktig at soldatene:
     - Er kjent med ildområde, ildåpningsbestemmelse, og grunnpunktene
     - Kooridnerer ildområdet mellom seg, slik at hele ildområdet er dekket. Bruke midten av målet(?)
     - At skuddfelt prioriteres før skjul og dekning.
     - Utbedrer stillingsområdet i den grad situasjonen tillater det.


** Stridsdrill 2: Ild og bevegelse
   Varighet: 15 minutter
   Metode: Modellbord med legofigurer
   
*** Kort innledning
    Stridsdrill 2 forteller hvordan vi skal manøvrere inn på fienden for å kunne gjøre innbrudd. Ledetråden her at all forflytning skjer under dekning av at deler av laget sikrer forflytningen til resten av laget.
    
*** Gjennomgang av drillen
    Drillen demonstreres ved hjelp av legofigurer.
    - (Intensjon/innledning) Lagfører varsler: Ild og bevegelse
    - (Retning) Videre gir lagfører ordre om retning til fienden.
    - (Formasjon) Deretter kommer ordren om organiseringen av laget. Eksempler:
      - Ildstøttegjeng
      - Ildstøttepar
    - (Metode) Så beskriver lagfører hvordan forflytningen skal skje, f.eks.
      - Lagvis
      - Gjengvis
      - Parvis
      - Makkervis
      - Enkeltvis
    - (Innbruddssted) Lagføreren gir ordre om hvor innbruddet skal gjøres.
    - (Ildledelse) Lagføreren gir en ildordre (EMU). Denne inneholder:
      - Hvem ordren gjelder for (enhet).
      - Hvor ilden skal treffe (målbeskrivelse og stedsangivelse).
      - Våpen/ammunisjonstype, hvor lenge ilden skal vare og hvilken hastighet det skal skytes, ildsort fra maskingevær (punktild, spredningsild, sperreild)
    - (Iverksettelse) Lagfører gir til slutt ordre om når ballet begynner.


*** Viktige momenter
    - Soldatene tilpasser forflytningsmetoden etter terreng og situasjon
    - Ved bruk av fremssprang skal man være maks 3 sekunder oppe, og kaste seg ned bak stillingen for så å åle seg frem til anleggsstilling.
    - Effektiv kommunikasjon
      - Grunnpunkter
      - Målangivelse
    - Lagfører plasserer seg hensiktsmessig for å beholde situasjonsforståelse og kommunikasjonsevne.
    - Formasjon tilpasses terreng
    - Soldaten søker etter mål, og beskyter skjulte og sannsynlige mål også.
    - Ammunisjonskontroll


** Stridsdrill 3a: Innbrudd i stilling/grop
   Varighet: 20 minutter
   Metode: Modellbord med legofigurer
   
*** Kort innledning
    Denne drillen beskriver metoden for å rydde individuelle ildstillinger og gjøre innbrudd i utbygde stillingssystemer. Avhengig av målets utseende benyttes enten
    * kast og storm, eller
    * kryp og kast


    Begge metodene utføres av makkerpar.
     
*** Gjennomgang av drillen
    *Kast og storm*
    
    Fase 1: Initiering. Kast og storm initieres med TA GROP. Videre: KLARGJØR SJOKK/SPLINT. Den som er best posisjonert til å kaste kvitterer MOTTATT og klargjør granaten, varsler SJOKK/SPLINT og melder kaster granaten opp i gropen. Den andre sikrer ved å opprettholder ild mot målet så den første får kastet, og melder TREFF eller BOM. Når granaten har truffet, skifter sikrer fokus mot dypet av målet. Ved bom gjentas prosedyren.

    Fase 2: Storm. Etter at granaten er gått av, stormes gropen. Den som kastet beordrer STORM, og fokuserer på selve gropen. Den som sikret følger etter og sikrer området rundt målet.

    Fase 3: Sikre målet. Den som kastet granaten forsikrer seg om at fienden er død og markerer "grop tatt." Sikrer kaster seg i nærmeste stilling bortenfor gropen og sikrer mot dypet. Beskyter synlige og sannsynlige mål.

    Fase 4: Sikre dypet og melde. Den som kastet søker nærmeste ildstilling etter at gropen er ryddet. Den som sikrer definerer midten av målet, og melder fra om innbrudd til lagfører. Begge beskyter synlige, sannsynlige og skjulte mål.

    *Kryp og kast*
    
    Denne metoden benyttes når:
     - Fienden er i en stilling med overdekning.
     - Laget er utsatt for en mulig trussel fra dypet.


    Fase 1: Initiering. Kryp og kast initieres med TA STILLING. Videre: KLARGJØR SJOKK/SPLINT. Den ene sikrer ved å skyte enkeltskudd mot stillingen. Den andre kvitterer MOTTATT og varsler SJOKK/SPLINT. Granaten kastes i forkant av stillingen for å tvinge fienden i dekning, og dekke at den som kastet når han kryper frem.

    Fase 2: Storm. Sikrer støtter kaster med ild så lenge det er sikkerhetsmessig forsvarlig. Etter det sikrer han dypet og gir observasjonsstøtte. Kaster kryper frem til stillingen og lemper en ny granat ned i stillingen.

    Fase 3: Sikre målet. Den som kastet granaten forsikrer seg om at fienden er død og markerer "grop tatt." Sikrer kryper fremover og støtter med observasjon og ild mot dypet. Sikrer kan enten følge den som kastet inn i stillingen, eller omgå den og finne en ildstilling på en av sidene. Beskyter synlige og sannsynlige mål.

    Fase 4: Sikre dypet og melde. Den som kastet søker nærmeste ildstilling etter at gropen er ryddet. Den som sikrer definerer midten av målet, og melder fra om innbrudd til lagfører. Begge beskyter synlige, sannsynlige og skjulte mål.
*** Viktige momenter
* Leksjon 2: Patruljetjeneste og kontakt
* Leksjon 3: MOBO
** Stridsdrill 4a: Rydding av rom
   Varighet: 40 minutter
   Metode: Demonstrasjon i rom avgrenset av sperrebånd e.l.
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Stridsdrill 4b: Innbrudd i bygning
   Varighet: 40 minutter
   Metode: Demonstrasjon i rom avgrenset av sperrebånd e.l.
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Stridsdrill 5a: Stridskontakt, vinne ildoverlegenhet
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Stridsdrill 5b: Stridskontakt, begrenset ildåpning
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Stridsdrill 5c: Ildstøtte, hurig angrep
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Stridsdrill 5d: Stridskontakt, kort hold
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
** Patruljeteknikk
*** Kort innledning
*** Gjennomgang av drillen
*** Viktige momenter
